### 后台用户登录
// @no-redirect  Login
POST {{domain}}/mgr-page/login
Content-Type: application/x-www-form-urlencoded

username={{be-username}}&password={{be-password}}

> {%
    client.test("Mgr-Page Login", function(){
        client.assert(response.status === 302, 'Response status is success');
    })
%}
