POST {{domain}}/api_v1/system/core/mock
Content-Type: application/json

{
    "timestamp": {{$timestamp}},
    "_py_sys_secret": {{py_secret}},
    "mock" : {
        "title" : "lexify|Role-????",
        "titleModify" : "lexify|Role-??????"
    }
}
> {%
     client.test("获取角色创建的数据并保存", function(){
        client.assert(response.status === 200, 'Response status is not 200');
        client.global.set('_title', response.body.data.title);
        client.global.set('_title_modify', response.body.data.titleModify);
    })
%}

###

GET {{domain}}/mgr-page/system/role?_scope={{be-role_scope}}&_query=1

> {%
     client.test("角色列表(View)", function(){
        client.assert(response.status === 200, 'Response status is not 200');
        client.assert(response.body.status === 0, 'Response status id not 0');
    })
%}

###

GET {{domain}}/mgr-page/system/role/establish?_query=1
X-Requested-With:  XMLHttpRequest

> {%
     client.test("创建角色(Condition)", function(){
        client.assert(response.status === 200, 'Response status is not 200');
    })
%}

###

POST {{domain}}/mgr-page/system/role/establish
Content-Type: application/x-www-form-urlencoded
X-Requested-With:  XMLHttpRequest

type={{be-role_scope}}&title={{_title}}

> {%
     client.test("创建角色", function(){
        client.assert(response.status === 200, 'Response status is not 200');
        client.assert(response.body.status === 0, 'Create Role Failed');
        client.global.set('_id', response.body.data.id);
    })
%}

###

GET {{domain}}/mgr-page/system/role/establish/{{_id}}?_query=1
X-Requested-With:  XMLHttpRequest

title={{_title_modify}}&type={{be-role_scope}}

> {%
     client.test("修改角色(条件)", function(){
        client.assert(response.status === 200, 'Response status is not 200');
        client.assert(response.body.status === 0, 'Modify Role Condition Failed');
    })
%}

###

POST {{domain}}/mgr-page/system/role/establish/{{_id}}
Content-Type: application/x-www-form-urlencoded
X-Requested-With:  XMLHttpRequest

title={{_title_modify}}&type={{be-role_scope}}

> {%
     client.test("修改角色", function(){
        client.assert(response.status === 200, 'Response status is not 200');
        client.assert(response.body.status === 0, 'Create Role Failed');
    })
%}

###

GET {{domain}}/mgr-page/system/role/delete/{{_id}}
X-Requested-With:  XMLHttpRequest

> {%
     client.test("删除角色", function(){
        client.assert(response.status === 200, 'Response status is not 200');
    })
%}
