POST {{domain}}/api_v1/system/core/mock
Content-Type: application/json

{
    "timestamp": {{$timestamp}},
    "_py_secret": {{py_secret}},
    "mock" : {
        "passport" : "phoneNumber",
        "password" : "lexify|????????"
    }
}
> {%
     client.test("获取账号创建的数据并保存", function(){
        client.assert(response.status === 200, 'Response status is not 200');
        client.global.set('_passport', response.body.data.passport)
        client.global.set('_password', response.body.data.password)
    })
%}

###
GET {{domain}}/mgr-page/system/pam?_query=1

> {%
    client.test("账号列表", function(){
        client.assert(response.status === 200, 'Response status is not 200');
    })
%}


###
GET {{domain}}/mgr-page/system/pam/establish?type=user&_query=1
X-Requested-With:  XMLHttpRequest

> {%
     client.test("账号创建(View)", function(){
        client.assert(response.status === 200, 'Response status is not 200');
    })
%}


###

POST {{domain}}/mgr-page/system/pam/establish
Content-Type: application/x-www-form-urlencoded
X-Requested-With:  XMLHttpRequest

username={{_passport}}&password={{_password}}&role_id[]={{be-role_id}}

> {%
     client.test("账号创建", function(){
        client.assert(response.status === 200, 'Response status is not 200');
        client.global.set('_id', response.body.data.id);
    })
%}

###
GET {{domain}}/mgr-page/system/pam/establish/{{_id}}?_query=1
X-Requested-With:  XMLHttpRequest

> {%
     client.test("获取账号信息", function(){
        client.assert(response.status === 200, 'Response status is not 200');
    })
%}

###
POST {{domain}}/mgr-page/system/pam/establish/{{_id}}
Content-Type: application/x-www-form-urlencoded
X-Requested-With:  XMLHttpRequest

password={{$uuid}}&role_id[]={{be-role_id}}

> {%
     client.test("修改账号信息", function(){
        client.assert(response.status === 200, 'Response status is not 200');
    })
%}


###
GET {{domain}}/mgr-page/system/pam/disable/{{_id}}?_query=1
X-Requested-With:  XMLHttpRequest

> {%
     client.test("禁用账号(View)", function(){
        client.assert(response.status === 200, 'Response status is not 200');
    })
%}

###
POST {{domain}}/mgr-page/system/pam/disable/{{_id}}
Content-Type: application/x-www-form-urlencoded
X-Requested-With:  XMLHttpRequest

date=2020-02-01&reason=Testing

> {%
     client.test("禁用账号", function(){
        client.assert(response.status === 200, 'Response status is not 200');
    })
%}


###
POST {{domain}}/mgr-page/system/pam/enable/{{_id}}
Content-Type: application/x-www-form-urlencoded
X-Requested-With:  XMLHttpRequest

> {%
     client.test("启用账号", function(){
        client.assert(response.status === 200, 'Response status is not 200');
    })
%}


###
GET {{domain}}/mgr-page/system/pam/log?_query=1

> {%
     client.test("获取登录日志", function(){
        client.assert(response.status === 200, 'Response status is not 200');
        client.assert(response.body.status === 0, 'Response status id not 0');
    })
%}
