<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateExamContentTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('exam_content', function (Blueprint $table) {
			$table->increments('id');
			$table->longText('title')->comment('问题内容');
			$table->string('type', 50)->default('select')->comment('问题类型 select:单选题 checkbox:多选题');
			$table->string('answer', 50)->default('')->comment('答案');
			$table->longText('options')->comment('选项');
			$table->nullableTimestamps();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('exam_content');
	}
}
