POST {{domain}}/api_v1/system/auth/login
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_sys_secret={{py_secret}}&passport={{passport}}&password={{password}}

> {%
    client.test("Login With User And Set User Token", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status === 0);
        client.global.set('token', response.body.data.token)
        client.log(client.global.get('token'));
    })
%}