###
POST {{domain}}/api_v1/system/auth/reset_password
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_sys_secret={{py_secret}}&passport={{passport}}&password={{_password}}

> {%
    client.test("根据手机号设置密码", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status ===0);
    })
%}
