###         name1
POST http://{{domain}}/api_v1/system/core/info
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_sys_secret={{py_secret}}

> {%
    client.test("Core Info Return Success", function(){
        client.log(JSON.stringify(response.body));
        client.assert(response.status === 200)
    })
%}

###
POST http://{{domain}}/api_v1/system/core/translate
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_sys_secret={{py_secret}}

> {%
    client.test("Translate Info Return Success", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status === 0)
    })
%}