### 发送验证码
POST {{domain}}/api_v1/system/captcha/send
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_secret={{py_secret}}&passport={{passport}}

> {%
    client.test("发送验证码", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status === 0);
    })
%}

### 获取验证码
POST {{domain}}/api_v1/system/captcha/fetch
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_secret={{py_secret}}&passport={{passport}}

> {%
    client.test("[L]获取验证码", function(){
        client.assert(response.status === 200);
        client.global.set('_captcha', response.body.data.captcha);
        client.log(client.global.get('_captcha'));
    })
%}


### 获取验证串
POST {{domain}}/api_v1/system/captcha/verify_code
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_secret={{py_secret}}&passport={{passport}}&captcha={{_captcha}}

> {%
    client.test("获取验证串", function(){
        client.assert(response.status === 200);
        client.global.set('_verify_code', response.body.data.verify_code);
        client.log(client.global.get('_verify_code'));
    })
%}

### 根据验证串重设密码
POST {{domain}}/api_v1/system/auth/reset_password
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_secret={{py_secret}}&verify_code={{_verify_code}}&password={{password}}

> {%
    client.test("根据验证串重设密码", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status ===0);
    })
%}


### 发送验证码
POST {{domain}}/api_v1/system/captcha/send
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_secret={{py_secret}}&passport={{passport}}

> {%
    client.test("发送验证码", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status === 0);
    })
%}

###
POST {{domain}}/api_v1/system/auth/reset_password
Content-Type: application/x-www-form-urlencoded

timestamp={{$timestamp}}&_py_secret={{py_secret}}&passport={{passport}}&captcha={{_captcha}}&password={{_password}}

> {%
    client.test("根据手机号设置密码", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status ===0);
    })
%}

### 换绑手机号
POST {{domain}}/api_v1/system/auth/bind_mobile
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}

timestamp={{$timestamp}}&_py_secret={{py_secret}}&passport={{passport}}&captcha={{_captcha}}&verify_code={{_verify_code}}

> {%
    client.test("绑定成功", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status ===0);
    })
%}