### Base64 上传图片
POST {{domain}}/api_v1/system/upload/image
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}

timestamp={{$timestamp}}&_py_sys_secret={{py_secret}}
&type=base64
&image[]={{image-base64}}
&image[]={{image-base64}}
&image[]={{image-base64}}

> {%
    client.test("Upload Image Use Type Base64", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status === 0);
        client.log(response.body.data.url);
    })
%}

### 文件上传图片
POST {{domain}}/api_v1/system/upload/image?timestamp={{$timestamp}}&_py_sys_secret={{py_secret}}
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=file

--file
Content-Disposition: form-data; name="image[]"; filename="sample.jpg"

< ../files/sample.jpg
--file
Content-Disposition: form-data; name="image[]"; filename="sample.png"

< ../files/sample.png
--file
Content-Disposition: form-data; name="image[]"; filename="sample.webp"

< ../files/sample.webp
--file--


### Url 上传图片
POST {{domain}}/api_v1/system/upload/image
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "timestamp" : "{{$timestamp}}",
    "_py_sys_secret" : "{{py_secret}}",
    "type" : "url",
    "image" : [
        "https://jdc.jd.com/img/100",
        "https://jdc.jd.com/img/500",
        "https://jdc.jd.com/img/1000"
    ]
}


### 上传图片并缩小
POST {{domain}}/api_v1/system/upload/image?timestamp={{$timestamp}}&_py_sys_secret={{py_secret}}&image_type=avatar
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=file

--file
Content-Disposition: form-data; name="image"; filename="480x640.jpg"

< ../files/480x640.jpg
--file--


### 上传音乐文件
POST {{domain}}/api_v1/system/upload/file?timestamp={{$timestamp}}&_py_sys_secret={{py_secret}}&type=audio
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=file

--file
Content-Disposition: form-data; name="file"; filename="actor.mp3"

< ../files/actor.mp3
--file--

